name: Repo Details

on:
 push: 
  branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
     image: preet182/docker-repo:ubuntusqlv2
  
    steps:
    - name: 'Checkout from Branch ${{ github.REF }}'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.REF }}
        fetch-depth: 0
      
    
  
