name: SQL Client

on:
 push:
  branches: [ main ]
  
jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
  - name: Docker Install
    run: |
      sudo apt update
      sudo apt install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
